const getMembers = require("./groups/getMembers"),
joinGroupManager = require("./groups/joinReq"),
invitesManager = require("./groups/invites"),
nicknames = require("./groups/nicknames"),
getGroup = require("./groups/getGroup"),
getRules = require("./groups/getRules"),
create = require("./groups/create"),
edit = require("./groups/edit"),
getUserGroups = require("./groups/getUserGroups"),
kick = require("./groups/kickMember"),
_delete = require("./groups/delete"),
rolesManager = require("./groups/roles")
module.exports = {
    getMembers,
    nicknames,
    getGroup,
    create,
    edit,
    _delete,
    getUserGroups,
    kick,
    getRules,
    rolesManager,
    joinGroupManager,
    invitesManager,
}